/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FooterApp: typeof import('./src/components/footerApp.vue')['default']
    HeaderApp: typeof import('./src/components/headerApp.vue')['default']
    LanguageSwitcher: typeof import('./src/components/languageSwitcher.vue')['default']
    LanguageSwitcherFixed: typeof import('./src/components/languageSwitcherFixed.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
